---
# tasks file for flexlm

# package {{{
- name: INSTALL FlexLM packages
  package:
    name: '{{ item }}'
    state: '{{ flexlm__packages_state }}'
    install_recommends: False
  with_flattened:
    - '{{ flexlm__dependent_packages }}'
  when: flexlm__packages_manage

# }}}

# user
- name: Create flexlm user
  user:
    name: '{{ flexlm__user_name }}'
    createhome: False
    system: True

# bin {{{
- name: Add lmgrd bin
  copy:
    src: '{{ flexlm__lmgrd_source + "." + flexlm__lmgrd_version }}'
    dest: '{{ flexlm__lmgrd_path + "." + flexlm__lmgrd_version }}'
    owner: '{{ flexlm__user_name }}'
    group: '{{ flexlm__user_name }}'
    mode: 0755

- name: Link to the last version of lmgrd
  file:
    src: '{{ flexlm__lmgrd_path + "." + flexlm__lmgrd_version }}'
    dest: '{{ flexlm__lmgrd_path }}'
    owner: '{{ flexlm__user_name }}'
    group: '{{ flexlm__user_name }}'
    state: link

- name: Add lmutil bin
  copy:
    src: '{{ flexlm__lmutil_source }}'
    dest: '{{ flexlm__lmutil_path }}'
    owner: '{{ flexlm__user_name }}'
    group: '{{ flexlm__user_name }}'
    mode: 0755

# }}}

# service {{{

- name: '{{ flexlm__service_name }} systemd service unit'
  template:
    src: '{{ flexlm__service_unit_content }}'
    dest: '{{ flexlm__service_unit_path }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: flexlm__register_systemd_service
  when: flexlm__service_manage

# }}}
