---
# tasks file for flexlm

# package {{{
- name: INSTALL FlexLM packages
  package:
    name: '{{ item }}'
    state: '{{ flexlm__packages_state }}'
    install_recommends: False
  with_flattened:
    - '{{ flexlm__dependent_packages }}'
  when: flexlm__packages_manage

# }}}

# bin
- name: Add lmgrd bin
  copy:
    src: '{{ flexlm__lmgrd_source + "." + flexlm__lmgrd_version }}'
    dest: '{{ flexlm__lmgrd_path + "." + flexlm__lmgrd_version }}'
    owner: root
    group: root
    mode: 0755

- name: Add lmutil bin
  copy:
    src: '{{ flexlm__lmutil_source }}'
    dest: '{{ flexlm__lmutil_path }}'
    owner: root
    group: root
    mode: 0755

