---
# handlers file for flexlm
- name: restart flexlm services
  service:
    name: '{{ "flexlm-" + item.name }}'
    state: '{{ "restarted" if (flexlm__deploy_state == "present" and (item.service | d(True) | bool)) else "stopped" }}'
    enabled: '{{ item.service | d(True) | bool }}'
  with_flattened:
    - '{{ flexlm__licences }}'

- name: systemd daemon reload
  systemd:
    daemon_reload: True
