---
# handlers file for flexlm
- name: restart flexlm services
  service:
    name: '{{ "flexlm-" + item.name }}'
    state: '{{ "restarted" if (flexlm__deploy_state == "present" and (item.service | d(True)) else "stopped" }}'
  with_flattened:
    - '{{ flexlm__licences }}'

