---
# handlers file for flexlm
- name: restart flexlm services
  service:
    name: '{{ "flexlm-" + item.name }}'
    state: restarted
  with_flattened:
    - '{{ flexlm__licences }}'
  when: ( flexlm__service_manage and
        ( item.service | d(True) ))
